title: FOIAlibs

# GitHub information
# This is used for adding an edit this page link to the footer
github:
  organization: 18F
  repository: federalist-uswds-template
  default_branch: master

theme: uswds-jekyll
